name: CI PIPELINE

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v3

      # Passo 2: Configura o Node.js com cache para acelerar builds futuros
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm" # Habilita cache das dependências

      # Passo 3: Instala as dependências de forma mais eficiente
      - name: Install dependencies
        run: npm ci # Usa npm ci para builds mais rápidos e consistentes

      # Passo 4: Executa os testes
      - name: Run tests
        run: npm test
